spring:
  datasource:
    url: jdbc:h2:mem:botdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: tgbot
    password: tgbot
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: true

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

app:
  webhookToken: "dev123"
  admins: [ 508490900 ]
  defaultAssignee: 508490900
  telegramEnabled: true

telegram:
  bot:
    username: "chxlsbot"
    token: "8140280578:AAHCWkoFKERJDYUZU2rhYPHyWCkLqt3YxOk"